### ISSUE TITLE
Can we a hint of how to using the .exe file created by Nemesis?

### ISSUE THREAD

**Issue by blueberrynotblue** [not-matthias/Nemesis#3]
**Is your feature request related to a problem? Please describe.**
Don't know how to use that dumped exe file.
**Describe the solution you'd like.**
I'd like to see a hint in README.MD. It might cost your a minute, but you will help a beginner a lot. thank you sir!

**Comment by not-matthias** [comment]
Hey, thanks for the feedback. I added a small section with a decompiler comparison to the README. Feel free to share your opinion, any suggestions and your feedback.
